### ISSUE TITLE
Menu Fails on some sites

### ISSUE THREAD

**Issue by krschmidt** [LaneCommunityCollege/megamenu#20]
Menu fails to drop down on https://blogs.lanecc.edu/studentsuccess -  but will eventually if you click enough

**Comment by krschmidt** [comment]
Also fails on blogs.lanecc.edu landing page

**Comment by krschmidt** [comment]
Issue appears to be that the megamenu gets loaded twice on those pages. @fotan could you fix them to only load the lmm.min.js script? In the mean time, I'll leave this issue pointing at me, since I should really detect if the menu has already been added, and end the script if it's there.

**Comment by fotan** [comment]
Fixed on blogs.lanecc.edu.  Also fixed on other Lane blogs that use the Weaver Xtreme theme.  I had fixed the problem before, but it looks like it showed back up when I used an old backup of the Weaver II settings.
