### ISSUE TITLE
Test version for unlaunched sites that the menu will search

### ISSUE THREAD

**Issue by jerrac** [LaneCommunityCollege/megamenu#21]
Can we get a test version of the menu that can be inserted on unlaunched sites? Specifically I want to add Connect to the search options, but I don't want that to be seen everywhere...

**Comment by krschmidt** [comment]
To test search functionality? Because Connect will get searched via Google CSE, so it'd fall under "Lane Websites", the default search option. And Google CSE doesn't support a test instance, and can only search public sites. I can add connect.lanecc.edu to our CSE definition though, and then you'd just be able to use the production megamenu for search testing.

**Comment by jerrac** [comment]
CSE will only see public content. That's not very useful when we (or at least, I) expect a significant portion of Connect to be private content visible only to logged in users. 

I can leave the Drupal search form on, but that's a bit odd when we also have search in the mega menu.

**Comment by krschmidt** [comment]
When upwards of 90% of megamenu viewers aren't going to be able to see Connect private content, why include that search in the megamenu for them?

**Comment by jerrac** [comment]
Those who don't use it, won't care that it's there. Those that do, will appreciate it.

Also, we'll need some version of a Connect specific search when we replace the directory with what's on Connect anyway.

Or, you could figure out a way to make having two search boxes on Connect sites less confusing. The best I've come up with is sticking it in the navbar where it will sit directly under the megamenu search box... The current location leaves a giant, empty, sidebar on most pages.

**Comment by krschmidt** [comment]
Providing an extra choice, that isn't a real option for the vast majority of users, is a negative pattern. 

Right now directory search works via CSE. It's my hope that we can eliminate the directory search option entirely and have CSE return people first always. Those should all be public pages on connect anyway.

Can the connect search be moved to a block on a sidebar?

**Comment by jerrac** [comment]
> Can the connect search be moved to a block on a sidebar?
> It is. That's why I said: "The current location leaves a giant, empty, sidebar on most pages."

Using CSE for the directory search is a idea I find terrible and we should discuss elsewhere when you are actually on the clock.

**Comment by krschmidt** [comment]
While CSE can be kinda clunky, I'd love to hear your rationale some time. I actually expect we'll be using it more, as there's a bunch of annotations I need to add some time. Currently, I'm pretty happy with how well it returns directory pages when searching for people. The only time it doesn't work is when you search a high profile person (on lots of news pages) or for a person with a last name that's on a ton of other pages (like Reagan, which competes with a ton of pages on Nancy Reagan), but I can combat that some I think with boost annotations.

In an ideal world, we'd include some role information in a cookie, and then multiple sites could use that to customize content based on role. If employee was present, we could show the connect search in the mm, and if student was present, we could not show the groupwise links.

Either way, we're past what could be considered an issue for the megamenu codebase.
